name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Package
        run: mvn clean package

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t wadiih/billing_back:${{ github.sha }} .
          docker login -u wadiih -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push wadiih/billing_back:${{ github.sha }}
